[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#02C75A"
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202020"
